# Generated by Django 4.2 on 2026-02-12 10:09

from django.db import migrations, models
import django.db.models.deletion
import marbella_informes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instal_lacio_nom', models.CharField(choices=[('marbella', 'MARBELLA')], max_length=32)),
                ('any', models.PositiveIntegerField(default=2026)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-any', 'instal_lacio_nom'],
                'unique_together': {('instal_lacio_nom', 'any')},
            },
        ),
        migrations.CreateModel(
            name='AnnualDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('clients', 'Clients / abonats'), ('reserves', 'Reserves d’espais')], max_length=32)),
                ('fitxer', models.FileField(upload_to=marbella_informes.models.annual_dataset_upload_path)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='marbella_informes.annualreport')),
            ],
            options={
                'ordering': ['tipus'],
                'unique_together': {('report', 'tipus')},
            },
        ),
    ]
