# Generated by Django 4.2 on 2026-02-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marbella_informes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreport',
            name='analysis_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='annualreport',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annualreport',
            name='status',
            field=models.CharField(default='draft', max_length=16),
        ),
    ]
