# Generated by Django 4.2 on 2026-02-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marbella_informes', '0002_annualreport_analysis_error_annualreport_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreport',
            name='status',
            field=models.CharField(default='draft', max_length=64),
        ),
    ]
