# Generated by Django 4.2 on 2026-02-16 09:18

from django.db import migrations, models
import marbella_informes.models


class Migration(migrations.Migration):

    dependencies = [
        ('marbella_informes', '0004_annualreport_analysis_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualdataset',
            options={'ordering': ['tipus', 'period', 'uploaded_at']},
        ),
        migrations.AlterUniqueTogether(
            name='annualdataset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='annualdataset',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualdataset',
            name='fitxer',
            field=models.FileField(blank=True, upload_to=marbella_informes.models.annual_dataset_upload_path),
        ),
        migrations.AlterField(
            model_name='annualdataset',
            name='tipus',
            field=models.CharField(choices=[('clients', 'Clients / abonats'), ('reserves', 'Reserves d’espais'), ('ocasionals', 'Ocasionals (mensual)')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='annualdataset',
            constraint=models.UniqueConstraint(condition=models.Q(('period__isnull', True)), fields=('report', 'tipus'), name='uniq_report_tipus_when_period_null'),
        ),
        migrations.AddConstraint(
            model_name='annualdataset',
            constraint=models.UniqueConstraint(condition=models.Q(('period__isnull', False)), fields=('report', 'tipus', 'period'), name='uniq_report_tipus_period_when_period_not_null'),
        ),
    ]
