# Generated by Django 4.2 on 2026-02-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marbella_informes', '0005_alter_annualdataset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreport',
            name='report_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='annualreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='marbella/%Y/reports/'),
        ),
        migrations.AddField(
            model_name='annualreport',
            name='report_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualreport',
            name='report_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annualreport',
            name='report_status',
            field=models.CharField(default='report_draft', max_length=64),
        ),
        migrations.CreateModel(
            name='AnnualReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='llm', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='marbella_informes.annualreport')),
            ],
            options={
                'unique_together': {('report', 'key')},
            },
        ),
    ]
