# Generated by Django 4.2 on 2026-01-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('input_partits', models.FileField(blank=True, null=True, upload_to='designacions/inputs/')),
                ('input_disponibilitats', models.FileField(blank=True, null=True, upload_to='designacions/inputs/')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('nif', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('modality', models.CharField(blank=True, max_length=120, null=True)),
                ('transport', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('engine_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('club_local', models.CharField(blank=True, max_length=255, null=True)),
                ('equip_local', models.CharField(blank=True, max_length=255, null=True)),
                ('equip_visitant', models.CharField(blank=True, max_length=255, null=True)),
                ('lliga', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('jornada', models.CharField(blank=True, max_length=50, null=True)),
                ('modality', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('hour_raw', models.CharField(blank=True, max_length=50, null=True)),
                ('domicile', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.CharField(blank=True, max_length=120, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_venue', models.CharField(blank=True, max_length=255, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='designacions.designationrun')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.JSONField(default=dict)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='designacions.referee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='designacions.designationrun')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='designacions.match')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='designacions.referee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='designacions.designationrun')),
            ],
        ),
    ]
