# Generated by Django 4.2 on 2026-01-21 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designacions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=500, unique=True)),
                ('municipality', models.CharField(blank=True, max_length=120, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('geocode_status', models.CharField(choices=[('pending', 'pending'), ('ok', 'ok'), ('not_found', 'not_found'), ('manual', 'manual')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModalityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddressCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='designacions.address')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_clusters', to='designacions.designationrun')),
            ],
            options={
                'unique_together': {('run', 'address')},
            },
        ),
    ]
