# Generated by Django 4.2 on 2026-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacions', '0002_address_modalitymap_addresscluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalitymap',
            name='codi_extern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modalitymap',
            name='descripcio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modalitymap',
            name='id_categoria',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='modalitymap',
            name='modalitat',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modalitymap',
            name='nom',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modalitymap',
            name='nom_abreviat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modalitymap',
            name='ordre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addresscluster',
            name='cluster_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='modalitymap',
            name='key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
