# Generated by Django 4.2 on 2026-01-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacions', '0003_modalitymap_codi_extern_modalitymap_descripcio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationrun',
            name='map_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='designationrun',
            name='result_summary',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
