# Generated by Django 4.2 on 2026-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacions', '0004_designationrun_map_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationrun',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
