"""Compatibility facade for legacy rotacions imports."""

from .views.rotacions import (
    estacio_delete,
    estacio_descans_create,
    estacions_reorder,
    franges_auto_create,
    franges_export_excel,
    franja_create,
    franja_delete,
    franja_insert_after,
    franja_order_mode_set,
    franja_update_inline,
    rotacions_clear_all,
    rotacions_extrapolar,
    rotacions_export_logo_clear,
    rotacions_export_logo_upload,
    rotacions_export_meta_save,
    rotacions_out_of_program_visibility_save,
    rotacions_planner,
    rotacions_save,
)

__all__ = [
    "estacio_delete",
    "estacio_descans_create",
    "estacions_reorder",
    "franges_auto_create",
    "franges_export_excel",
    "franja_create",
    "franja_delete",
    "franja_insert_after",
    "franja_order_mode_set",
    "franja_update_inline",
    "rotacions_clear_all",
    "rotacions_extrapolar",
    "rotacions_export_logo_clear",
    "rotacions_export_logo_upload",
    "rotacions_export_meta_save",
    "rotacions_out_of_program_visibility_save",
    "rotacions_planner",
    "rotacions_save",
]
