# Generated by Codex on 2026-03-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("competicions_trampoli", "0039_aparell_created_by_phase1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aparell",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aparells_creats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="aparell",
            constraint=models.UniqueConstraint(
                fields=("created_by", "codi"),
                name="uniq_aparell_created_by_codi",
            ),
        ),
    ]
