# Generated by Codex on 2026-03-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("competicions_trampoli", "0041_classificacio_template_owner_phase1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificaciotemplateglobal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classificacio_templates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="classificaciotemplateglobal",
            constraint=models.UniqueConstraint(
                fields=("created_by", "slug"),
                name="uniq_classif_tpl_owner_slug",
            ),
        ),
    ]
