# Generated by Django 4.2 on 2026-04-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicions_trampoli', '0053_contextualize_equip'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rotacioassignacioserieequip',
            new_name='competicion_serie_i_c97877_idx',
            old_name='competicion_serie_i_24c55a_idx',
        ),
        migrations.RenameIndex(
            model_name='serieequip',
            new_name='competicion_competi_531993_idx',
            old_name='competicion_competi_8b69dd_idx',
        ),
        migrations.RenameIndex(
            model_name='serieequipitem',
            new_name='competicion_serie_i_4b524d_idx',
            old_name='competicion_serie_i_6cf549_idx',
        ),
        migrations.RenameIndex(
            model_name='serieequipitem',
            new_name='competicion_team_su_18d79b_idx',
            old_name='competicion_team_s_8a272e_idx',
        ),
    ]
